### PR TITLE
Making Changes to listings_single.html

### PR DESCRIPTION
**Pull request by brindasachi97**

### CODE REVIEW

**Comment by dannyi96** [comment]
Did you delete `listings_single.html` by mistake?
It shows there are no changes

**Comment by brindasachi97** [comment]
I forked it and added listings_single.html outside the real-estate folder
by mistake. So deleted that. Dhanush has the most latest version. He would
upload it in a bit.

The original listings_single.html still exists.

**Comment by dannyi96** [comment]
Okay 👍

**Comment by dannyi96** [comment]
Upload the latest version here when it's done

**Comment by brindasachi97** [comment]
Sure

**Comment by dannyi96** [comment]
solved by #9

**Pull request closed without merging**
